# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 01:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flipbooks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frame',
            name='note',
            field=models.TextField(blank=True, default='', max_length=100),
        ),
    ]
