# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-30 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flipbooks', '0002_auto_20170626_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='frame',
            name='frame_image',
            field=models.ImageField(blank=True, upload_to='frame_images/'),
        ),
    ]
