# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-01 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flipbooks', '0004_auto_20170801_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='frame',
            name='order',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='scene',
            name='order',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='strip',
            name='order',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='frame',
            name='note',
            field=models.CharField(blank=True, default='', help_text="This note will not be visible for viewers. It's just for the creator", max_length=100),
        ),
    ]
