# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-15 15:27
from __future__ import unicode_literals

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('flipbooks', '0005_auto_20170801_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frame',
            name='frame_image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to='frame_images/thumbTest/'),
        ),
    ]
