# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-15 20:01
from __future__ import unicode_literals

from django.db import migrations
import easy_thumbnails.fields
import flipbooks.models


class Migration(migrations.Migration):

    dependencies = [
        ('flipbooks', '0006_auto_20170815_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frame',
            name='frame_image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to=flipbooks.models.frame_upload_path),
        ),
    ]
