# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-15 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flipbooks', '0007_auto_20170815_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
