# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-20 01:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flipbooks', '0008_scene_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='order_list',
            field=models.TextField(default='[]'),
        ),
    ]
