# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-20 02:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flipbooks', '0009_scene_order_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scene',
            name='order_list',
            field=models.TextField(default='[]', max_length=200),
        ),
    ]
