# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-28 11:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flipbooks', '0011_auto_20170920_2008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Untitled Book', max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default='0')),
                ('title', models.CharField(blank=True, default='Untitled', max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flipbooks.Book')),
            ],
        ),
        migrations.AddField(
            model_name='scene',
            name='chapter',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='flipbooks.Chapter'),
        ),
    ]
