# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-29 23:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flipbooks', '0012_auto_20170928_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scene',
            name='chapter',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='flipbooks.Chapter'),
        ),
    ]
