# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-29 23:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flipbooks', '0013_auto_20170929_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scene',
            name='children_orders',
            field=models.TextField(blank=True, default='', max_length=200),
        ),
    ]
