# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-14 18:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flipbooks', '0018_auto_20180113_2151'),
    ]

    operations = [
        migrations.RenameField('scene', 'children_orders', 'children_li'),
        migrations.RenameField('strip', 'children_orders', 'children_li'),
    ]
