# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-14 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flipbooks', '0019_auto_20180114_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frame',
            name='order',
            field=models.IntegerField(default='-1'),
        ),
    ]
