# Generated by Django 2.1.1 on 2018-10-12 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flipbooks', '0023_auto_20181006_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='strip',
            name='dimension',
            field=models.CharField(blank=True, default='', max_length=9),
        ),
    ]
