# Generated by Django 2.1.1 on 2018-10-13 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flipbooks', '0025_frame_dimension'),
    ]

    operations = [
        migrations.AddField(
            model_name='frame',
            name='ignored',
            field=models.BooleanField(default=False),
        ),
    ]
