# Generated by Django 2.1.1 on 2018-10-25 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flipbooks', '0026_frame_ignored'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.SlugField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(default='Untitled Book', max_length=50),
        ),
    ]
