# Generated by Django 2.1.1 on 2018-10-26 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flipbooks', '0027_auto_20181025_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='id64',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
    ]
