# Generated by Django 2.1.1 on 2018-11-11 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flipbooks', '0029_auto_20181028_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='strip',
            name='frame_duration',
            field=models.IntegerField(blank=True, default='400', max_length=4),
        ),
    ]
