# Generated by Django 2.1.1 on 2018-11-19 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flipbooks', '0031_auto_20181111_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='frame',
            name='is_mirroring',
            field=models.BooleanField(default=False),
        ),
    ]
