# Generated by Django 2.1.1 on 2018-12-03 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flipbooks', '0032_frame_is_mirroring'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='id64',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
    ]
