# Generated by Django 2.1.5 on 2019-02-22 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flipbooks', '0034_chapter_is_demo'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='movie',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
