# Generated by Django 2.1.5 on 2019-02-23 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flipbooks', '0035_scene_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='movie_url',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
    ]
