# Generated by Django 2.1.5 on 2019-02-27 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flipbooks', '0036_scene_movie_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='playback',
            field=models.TextField(blank=True, default=''),
        ),
    ]
