# Generated by Django 3.0.6 on 2020-05-27 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flipbooks', '0038_episode_series'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Series',
            new_name='Oldseries',
        ),
        migrations.RenameField(
            model_name='episode',
            old_name='series',
            new_name='oldseries',
        ),
    ]
