# Generated by Django 3.0.6 on 2020-05-31 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storypiper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flipbook',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='storypiper.Series'),
        ),
    ]
